export const CONTRACTS = {
  AGENT_REGISTRY: '0x0C4B4a963c54CB997E5a4d8D5B58c14720963b10',
  PAYMENT_ROUTER: '0xFcd61490199B26E65C74eFc44a710736A7cBb695',
  REPUTATION_ENGINE: '0x6c6b13DA392c25696c249c18e5D53f7Cb73db7cF', // Managed by PaymentRouter
  USDC: '0x3600000000000000000000000000000000000000',
};

export const CHAIN_CONFIG = {
  id: 5042002,
  name: 'Arc Network',
  rpc: 'https://rpc.testnet.arc.network',
};

export const AGENT_REGISTRY_ABI = [
  { "type": "function", "name": "agentCount", "inputs": [], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" },
  { "type": "function", "name": "getAgent", "inputs": [{ "name": "agentId", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "tuple", "internalType": "struct AgentRegistry.AgentInfo", "components": [{ "name": "owner", "type": "address", "internalType": "address" }, { "name": "payoutAddress", "type": "address", "internalType": "address" }, { "name": "pricePerCall", "type": "uint96", "internalType": "uint96" }, { "name": "name", "type": "string", "internalType": "string" }, { "name": "description", "type": "string", "internalType": "string" }, { "name": "endpoint", "type": "string", "internalType": "string" }, { "name": "active", "type": "bool", "internalType": "bool" }] }], "stateMutability": "view" },
  { "type": "function", "name": "listAgents", "inputs": [{ "name": "offset", "type": "uint256", "internalType": "uint256" }, { "name": "limit", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "agents", "type": "tuple[]", "internalType": "struct AgentRegistry.AgentInfo[]", "components": [{ "name": "owner", "type": "address", "internalType": "address" }, { "name": "payoutAddress", "type": "address", "internalType": "address" }, { "name": "pricePerCall", "type": "uint96", "internalType": "uint96" }, { "name": "name", "type": "string", "internalType": "string" }, { "name": "description", "type": "string", "internalType": "string" }, { "name": "endpoint", "type": "string", "internalType": "string" }, { "name": "active", "type": "bool", "internalType": "bool" }] }], "stateMutability": "view" },
  { "type": "function", "name": "registerAgent", "inputs": [{ "name": "name", "type": "string", "internalType": "string" }, { "name": "description", "type": "string", "internalType": "string" }, { "name": "pricePerCall", "type": "uint96", "internalType": "uint96" }, { "name": "endpoint", "type": "string", "internalType": "string" }, { "name": "payoutAddress", "type": "address", "internalType": "address" }], "outputs": [{ "name": "agentId", "type": "uint256", "internalType": "uint256" }], "stateMutability": "nonpayable" },
  { "type": "event", "name": "AgentRegistered", "inputs": [{ "name": "agentId", "type": "uint256", "indexed": true, "internalType": "uint256" }, { "name": "owner", "type": "address", "indexed": true, "internalType": "address" }, { "name": "payoutAddress", "type": "address", "indexed": false, "internalType": "address" }], "anonymous": false }
] as const;

export const PAYMENT_ROUTER_ABI = [
  { "type": "function", "name": "tasks", "inputs": [{ "name": "", "type": "bytes32", "internalType": "bytes32" }], "outputs": [{ "name": "agentId", "type": "uint256", "internalType": "uint256" }, { "name": "payer", "type": "address", "internalType": "address" }, { "name": "claimer", "type": "address", "internalType": "address" }, { "name": "payoutAddress", "type": "address", "internalType": "address" }, { "name": "createdAt", "type": "uint64", "internalType": "uint64" }, { "name": "deadline", "type": "uint64", "internalType": "uint64" }, { "name": "reward", "type": "uint96", "internalType": "uint96" }, { "name": "expectedResultHash", "type": "bytes32", "internalType": "bytes32" }, { "name": "verifier", "type": "address", "internalType": "address" }, { "name": "status", "type": "uint8", "internalType": "enum PaymentRouter.TaskStatus" }, { "name": "taskData", "type": "bytes", "internalType": "bytes" }, { "name": "authValidAfter", "type": "uint64", "internalType": "uint64" }, { "name": "authValidBefore", "type": "uint64", "internalType": "uint64" }, { "name": "authNonce", "type": "bytes32", "internalType": "bytes32" }, { "name": "authV", "type": "uint8", "internalType": "uint8" }, { "name": "authR", "type": "bytes32", "internalType": "bytes32" }, { "name": "authS", "type": "bytes32", "internalType": "bytes32" }], "stateMutability": "view" },
  { "type": "function", "name": "routePayment", "inputs": [{ "name": "agentId", "type": "uint256", "internalType": "uint256" }, { "name": "taskData", "type": "bytes", "internalType": "bytes" }, { "name": "reward", "type": "uint96", "internalType": "uint96" }, { "name": "deadline", "type": "uint64", "internalType": "uint64" }, { "name": "verifier", "type": "address", "internalType": "address" }, { "name": "expectedResultHash", "type": "bytes32", "internalType": "bytes32" }, { "name": "authValidAfter", "type": "uint64", "internalType": "uint64" }, { "name": "authValidBefore", "type": "uint64", "internalType": "uint64" }, { "name": "authNonce", "type": "bytes32", "internalType": "bytes32" }, { "name": "authV", "type": "uint8", "internalType": "uint8" }, { "name": "authR", "type": "bytes32", "internalType": "bytes32" }, { "name": "authS", "type": "bytes32", "internalType": "bytes32" }], "outputs": [{ "name": "taskId", "type": "bytes32", "internalType": "bytes32" }], "stateMutability": "nonpayable" },
  { "type": "function", "name": "claimTask", "inputs": [{ "name": "taskId", "type": "bytes32", "internalType": "bytes32" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "settlePayment", "inputs": [{ "name": "taskId", "type": "bytes32", "internalType": "bytes32" }, { "name": "result", "type": "bytes", "internalType": "bytes" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "function", "name": "cancel", "inputs": [{ "name": "taskId", "type": "bytes32", "internalType": "bytes32" }], "outputs": [], "stateMutability": "nonpayable" },
  { "type": "event", "name": "TaskRouted", "inputs": [{ "name": "taskId", "type": "bytes32", "indexed": true, "internalType": "bytes32" }, { "name": "agentId", "type": "uint256", "indexed": true, "internalType": "uint256" }, { "name": "payer", "type": "address", "indexed": true, "internalType": "address" }, { "name": "reward", "type": "uint256", "indexed": false, "internalType": "uint256" }], "anonymous": false },
  { "type": "event", "name": "TaskClaimed", "inputs": [{ "name": "taskId", "type": "bytes32", "indexed": true, "internalType": "bytes32" }, { "name": "claimer", "type": "address", "indexed": true, "internalType": "address" }], "anonymous": false },
  { "type": "event", "name": "TaskCompleted", "inputs": [{ "name": "taskId", "type": "bytes32", "indexed": true, "internalType": "bytes32" }, { "name": "success", "type": "bool", "indexed": false, "internalType": "bool" }], "anonymous": false }
] as const;

export const REPUTATION_ENGINE_ABI = [
  { "type": "function", "name": "getScore", "inputs": [{ "name": "agentId", "type": "uint256", "internalType": "uint256" }], "outputs": [{ "name": "", "type": "uint256", "internalType": "uint256" }], "stateMutability": "view" }
] as const;
